apply plugin: 'java'
//apply plugin: 'kotlin'
//apply plugin: 'com.android.library'

targetCompatibility = JavaVersion.VERSION_11
sourceCompatibility = JavaVersion.VERSION_11

configurations {
    lintChecks
}

dependencies {
    implementation "com.android.tools.lint:lint-api:$LINT_VERSION"
    implementation "com.android.tools.lint:lint-checks:$LINT_VERSION"
    implementation "com.android.tools.lint:lint:$LINT_VERSION"

//    implementation "androidx.core:core:1.7.0"
//    implementation "androidx.fragment:fragment:$ANDROIDX_FRAGMENT"

    testImplementation "junit:junit:$JUNIT_VERSION"
    testImplementation "com.android.tools.lint:lint-tests:$LINT_VERSION"
    testImplementation "com.android.tools:testutils:$LINT_VERSION"

    lintChecks files(jar)
}

jar {
    manifest {
        attributes("Lint-Registry-v2": "permissions.dispatcher.PermissionsDispatcherIssueRegistry")
    }
}
